<?php
/**
 * generated by purehp version 0.1.0.0
 */
declare(strict_types=1);



class Functions {
    public function __construct() {
        $this->fun1 = function ($arg) { // TODO leave here or move to a static function?
            return $arg;
        };
    }
}

?>
