<?php
/**
 * generated by purehp version 0.1.0.0
 */
declare(strict_types=1);



$__Functions_Inner = new \Functions\Inner();
class Functions {
    public function __construct() {
        $this->foo = self::fun2(1)(2);
        $this->bar = $__Functions_Inner->fun3(5);
    }
    public static function fun2($v) {
        return function ($b) use ($v) {
            return $b;
        };
    }
}

?>
