<?php
/**
 * generated by purehp version 0.1.0.0
 */
declare(strict_types=1);



class Functions {
    public function __construct() {
        $this->foo = self->TEST = $fun2;(1)(2);
    }
    public static function fun2($v) {
        return function ($b) use ($v) {
            return $b;
        };
    }
}

?>
