<?php
/**
 * generated by purehp version 0.1.0.0
 */
declare(strict_types=1);

class Let {
    public function __construct() {
        $this->foo = (function () {
            $a = 1;
            return $a;
        })();
    }
}

?>
