<?php
/**
 * generated by purehp version 0.1.0.0
 */

namespace Literals;

$string1 = "Hello World!";
$rec1 = (object) ['x' => 1, 'y' => "Hello", 'z' => function ($x) {
    return $x;
}];
$int1 = 5;
$int2 = $int1;
$char1 = "C";
$array1 = [1, 2, 3, 4];

?>
